import AppKit
import Defaults
import Sauce

class Clipboard {
    static let shared = Clipboard()

    typealias OnNewCopyHook = (ClipboardItem, Bool) -> Void

    private var onNewCopyHooks: [OnNewCopyHook] = []
    var changeCount: Int
    private var lastClipboardChangeTime: Date?
    private var lastClipboardContent: String?

    private let pasteboard = NSPasteboard.general

    private var timer: Timer?

    private let dynamicTypePrefix = "dyn."
    private let microsoftSourcePrefix = "com.microsoft.ole.source."
    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL,
        .heic,
        .html,
        .jpeg,
        .png,
        .rtf,
        .string,
        .tiff,
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated,
        .concealed,
        .transient,
    ]

    private var enabledTypes: Set<NSPasteboard.PasteboardType> {
        Defaults[.enabledPasteboardTypes]
    }

    private var disabledTypes: Set<NSPasteboard.PasteboardType> {
        supportedTypes.subtracting(enabledTypes)
    }

    private var sourceApp: NSRunningApplication? {
        NSWorkspace.shared.frontmostApplication
    }

    init() {
        changeCount = pasteboard.changeCount
    }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHooks.append(hook)
    }

    func clearHooks() {
        onNewCopyHooks = []
    }

    func start() {
        timer = Timer.scheduledTimer(
            timeInterval: Defaults[.clipboardCheckInterval],
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
    }

    func restart() {
        timer?.invalidate()
        start()
    }

    @MainActor
    func copy(_ string: String) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        sync()
        checkForChangesInPasteboard()
    }

    @MainActor
    func copy(_ item: ClipboardItem?, removeFormatting: Bool = false) {
        guard let item else { return }

        pasteboard.clearContents()
        var contents = item.contents

        if removeFormatting {
            contents = clearFormatting(contents)
        }

        for content in contents {
            guard content.contentType != NSPasteboard.PasteboardType.fileURL.rawValue else { continue }
            if let value = content.value {
                pasteboard.setData(value, forType: NSPasteboard.PasteboardType(content.contentType))
            }
        }

        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.contentType == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
            guard let value = content.value else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.contentType))
            return pasteItem
        }
        pasteboard.writeObjects(fileURLItems)

        pasteboard.setString("", forType: .fromManisPocket)
        pasteboard.setString(item.application ?? "", forType: .source)
        sync()

        Task {
            Notifier.notify(body: item.title, sound: .knock)
            checkForChangesInPasteboard()
        }
    }

    func paste() {
        Accessibility.check()

        let cmdFlag = CGEventFlags(rawValue: UInt64(KeyChord.pasteKeyModifiers.rawValue) | 0x000008)
        var vCode = Sauce.shared.keyCode(for: KeyChord.pasteKey)

        if KeyboardLayout.current.commandSwitchesToQWERTY, cmdFlag.contains(.maskCommand) {
            vCode = KeyChord.pasteKey.QWERTYKeyCode
        }

        let source = CGEventSource(stateID: .combinedSessionState)
        source?.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents],
                                                           state: .eventSuppressionStateSuppressionInterval)

        let keyVDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
        let keyVUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
        keyVDown?.flags = cmdFlag
        keyVUp?.flags = cmdFlag
        keyVDown?.post(tap: .cgSessionEventTap)
        keyVUp?.post(tap: .cgSessionEventTap)
    }

    func clear() {
        guard Defaults[.clearSystemClipboard] else {
            return
        }

        pasteboard.clearContents()
    }

    @objc
    @MainActor
    func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else {
            return
        }

        let previousChangeCount = changeCount
        changeCount = pasteboard.changeCount
        let changeCountDelta = changeCount - previousChangeCount

        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromManisPocket) }) != true {
            AppState.shared.history.interruptPasteStack()
        }

        if Defaults[.ignoreEvents] {
            if Defaults[.ignoreOnlyNextEvent] {
                Defaults[.ignoreEvents] = false
                Defaults[.ignoreOnlyNextEvent] = false
            }

            return
        }

        if shouldIgnore(Set(pasteboard.types ?? [])) {
            return
        }

        if let sourceAppBundle = sourceApp?.bundleIdentifier, shouldIgnore(sourceAppBundle) {
            return
        }

        var contents = [ClipboardContent]()
        pasteboard.pasteboardItems?.forEach { item in
            var types = Set(item.types)
            if types.contains(.string), isEmptyString(item), !richText(item) {
                return
            }

            if shouldIgnore(item) {
                return
            }

            types = types
                .subtracting(disabledTypes)
                .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
                .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

            if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
                types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
            }

            for type in types {
                if let data = item.data(forType: type) {
                    contents.append(ClipboardContent(contentType: type.rawValue, value: data))
                }
            }
        }

        guard !contents.isEmpty else {
            return
        }

        let nowMs = Int64(Date().timeIntervalSince1970 * 1000)
        var clipboardItem = ClipboardItem(
            id: UUID().uuidString,
            application: sourceApp?.bundleIdentifier
                ?? contents.first(where: { $0.contentType == NSPasteboard.PasteboardType.source.rawValue })?.value
                .flatMap { String(data: Data($0), encoding: .utf8) },
            firstCopiedAt: nowMs,
            lastCopiedAt: nowMs,
            numberOfCopies: 1,
            pin: nil,
            title: "",
            contents: contents,
            syncTimestamp: nowMs,
            syncSource: nil,
            syncDeleted: false
        )
        clipboardItem.title = generateTitle(for: clipboardItem)
        if clipboardItem.application == nil || clipboardItem.application?.isEmpty == true {
            NSLog("[Clipboard] new item has nil/empty application — sourceApp.bundleIdentifier=\(sourceApp?.bundleIdentifier ?? "nil") frontmostApp=\(String(describing: sourceApp?.localizedName))")
        }

        var shouldAppend = false
        let now = Date.now
        let currentContent = getText(from: clipboardItem)

        if Defaults[.appendModeEnabled] {
            if changeCountDelta == 2 {
                shouldAppend = true
            } else if let lastChange = lastClipboardChangeTime,
                      let lastContent = lastClipboardContent,
                      let currentText = currentContent
            {
                if currentText == lastContent {
                    let timeSinceLastChange = now.timeIntervalSince(lastChange)
                    if timeSinceLastChange <= Defaults[.appendModeTimeWindow] {
                        shouldAppend = true
                    }
                }
            }
        }

        if !shouldAppend {
            lastClipboardChangeTime = now
            lastClipboardContent = currentContent
        }

        onNewCopyHooks.forEach { $0(clipboardItem, shouldAppend) }
    }

    // MARK: - Title Generation (stays in Swift for AppKit/Vision dependencies)

    func generateTitle(for item: ClipboardItem) -> String {
        guard getImageData(from: item) == nil else {
            return "" // Image title will be set later via OCR
        }

        var title = getPreviewableText(from: item).shortened(to: 1000)

        if Defaults[.showSpecialSymbols] {
            if let range = title.range(of: "^ +", options: .regularExpression) {
                title = title.replacingOccurrences(of: " ", with: "·", range: range)
            }
            if let range = title.range(of: " +$", options: .regularExpression) {
                title = title.replacingOccurrences(of: " ", with: "·", range: range)
            }
            title = title
                .replacingOccurrences(of: "\n", with: "⏎")
                .replacingOccurrences(of: "\t", with: "⇥")
        } else {
            title = title.trimmingCharacters(in: .whitespacesAndNewlines)
        }

        return title
    }

    // MARK: - Content Helpers

    func getText(from item: ClipboardItem) -> String? {
        guard let content = item.contents.first(where: { $0.contentType == NSPasteboard.PasteboardType.string.rawValue }),
              let value = content.value else { return nil }
        return String(data: value, encoding: .utf8)
    }

    func getImageData(from item: ClipboardItem) -> Data? {
        let imageTypes = [NSPasteboard.PasteboardType.tiff, .png, .jpeg, .heic].map(\.rawValue)
        guard let content = item.contents.first(where: { imageTypes.contains($0.contentType) }),
              let value = content.value else { return nil }
        return value
    }

    func getPreviewableText(from item: ClipboardItem) -> String {
        let fileURLType = NSPasteboard.PasteboardType.fileURL.rawValue
        let fileURLContents = item.contents.filter { $0.contentType == fileURLType }
        if !fileURLContents.isEmpty {
            let urls = fileURLContents.compactMap { content -> String? in
                guard let value = content.value else { return nil }
                let url = URL(dataRepresentation: value, relativeTo: nil, isAbsolute: true)
                return url?.absoluteString.removingPercentEncoding
            }
            if !urls.isEmpty {
                return urls.joined(separator: "\n")
            }
        }

        if let text = getText(from: item), !text.isEmpty {
            return text
        }

        if let rtfContent = item.contents.first(where: { $0.contentType == NSPasteboard.PasteboardType.rtf.rawValue }),
           let value = rtfContent.value,
           let attributed = NSAttributedString(rtf: value, documentAttributes: nil),
           !attributed.string.isEmpty
        {
            return attributed.string
        }

        if let htmlContent = item.contents.first(where: { $0.contentType == NSPasteboard.PasteboardType.html.rawValue }),
           let value = htmlContent.value,
           let attributed = NSAttributedString(html: value, documentAttributes: nil),
           !attributed.string.isEmpty
        {
            return attributed.string
        }

        return item.title
    }

    func isFromManisPocket(_ item: ClipboardItem) -> Bool {
        item.contents.contains(where: { $0.contentType == NSPasteboard.PasteboardType.fromManisPocket.rawValue })
    }

    // MARK: - Private Helpers

    private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
        let ignoredTypes = ignoredTypes
            .union(Defaults[.ignoredPasteboardTypes].map { NSPasteboard.PasteboardType($0) })

        return types.isDisjoint(with: enabledTypes) ||
            !types.isDisjoint(with: ignoredTypes)
    }

    private func shouldIgnore(_ sourceAppBundle: String) -> Bool {
        if Defaults[.ignoreAllAppsExceptListed] {
            !Defaults[.ignoredApps].contains(sourceAppBundle)
        } else {
            Defaults[.ignoredApps].contains(sourceAppBundle)
        }
    }

    private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
        for regexp in Defaults[.ignoreRegexp] {
            if let string = item.string(forType: .string) {
                do {
                    let regex = try NSRegularExpression(pattern: regexp)
                    if regex.numberOfMatches(in: string, range: NSRange(string.startIndex..., in: string)) > 0 {
                        return true
                    }
                } catch {
                    return false
                }
            }
        }
        return false
    }

    private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else {
            return true
        }

        return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func richText(_ item: NSPasteboardItem) -> Bool {
        if let rtf = item.data(forType: .rtf) {
            if let attributedString = NSAttributedString(rtf: rtf, documentAttributes: nil) {
                return !attributedString.string.isEmpty
            }
        }

        if let html = item.data(forType: .html) {
            if let attributedString = NSAttributedString(html: html, documentAttributes: nil) {
                return !attributedString.string.isEmpty
            }
        }

        return false
    }

    private func sync() {
        guard let app = sourceApp,
              app.bundleURL?.lastPathComponent == "Chrome Remote Desktop.app" ||
              app.localizedName?.contains("NetBeans") == true
        else {
            return
        }

        NSApp.activate(ignoringOtherApps: true)
        NSApp.hide(self)
    }

    private func clearFormatting(_ contents: [ClipboardContent]) -> [ClipboardContent] {
        var newContents: [ClipboardContent] = contents
        let stringContents = contents.filter { $0.contentType == NSPasteboard.PasteboardType.string.rawValue }

        if !stringContents.isEmpty {
            newContents = stringContents

            let fileURLContents = contents.filter { $0.contentType == NSPasteboard.PasteboardType.fileURL.rawValue }
            if !fileURLContents.isEmpty {
                newContents += fileURLContents
            }
        }

        return newContents
    }
}
