// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ManisPocketCoreFFI)
import ManisPocketCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_manis_pocket_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_manis_pocket_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureManisPocketCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Callback interface that platforms implement to receive sync events.
 * Platforms (Swift/Kotlin) implement this via UniFFI foreign trait.
 */
public protocol ClipboardObserver: AnyObject, Sendable {

    /**
     * A new clipboard item was received from a synced peer.
     */
    func onItemReceived(item: ClipboardItem)

    /**
     * An item was deleted by a synced peer.
     */
    func onItemDeleted(itemId: String)

    /**
     * An item was updated (e.g., appended) by a synced peer.
     */
    func onItemUpdated(item: ClipboardItem)

    /**
     * A peer was discovered on the network.
     */
    func onPeerDiscovered(peerId: String, displayName: String, addresses: [String], isConnected: Bool)

    /**
     * A peer disconnected or went offline.
     */
    func onPeerLost(peerId: String)

    /**
     * A pairing request was received from a peer.
     */
    func onPairingRequest(peerId: String, displayName: String, pin: String)

    /**
     * A pairing request completed (accepted or rejected).
     */
    func onPairingComplete(peerId: String, success: Bool)

    /**
     * Sync is now listening on the given multiaddress.
     */
    func onListening(address: String)

    /**
     * An error occurred in the sync engine.
     */
    func onError(code: Int32, message: String)

    /**
     * A file chunk was received (append to local temp file).
     */
    func onFileChunk(requestId: String, fileName: String, fileSize: Int64, chunkIndex: Int32, totalChunks: Int32, data: Data)

    /**
     * File download completed (or failed).
     */
    func onFileDownloadComplete(requestId: String, filePath: String, success: Bool)

}
/**
 * Callback interface that platforms implement to receive sync events.
 * Platforms (Swift/Kotlin) implement this via UniFFI foreign trait.
 */
open class ClipboardObserverImpl: ClipboardObserver, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_manis_pocket_core_fn_clone_clipboardobserver(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_manis_pocket_core_fn_free_clipboardobserver(handle, $0) }
    }




    /**
     * A new clipboard item was received from a synced peer.
     */
open func onItemReceived(item: ClipboardItem)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_item_received(
            self.uniffiCloneHandle(),
        FfiConverterTypeClipboardItem_lower(item),$0
    )
}
}

    /**
     * An item was deleted by a synced peer.
     */
open func onItemDeleted(itemId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_item_deleted(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(itemId),$0
    )
}
}

    /**
     * An item was updated (e.g., appended) by a synced peer.
     */
open func onItemUpdated(item: ClipboardItem)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_item_updated(
            self.uniffiCloneHandle(),
        FfiConverterTypeClipboardItem_lower(item),$0
    )
}
}

    /**
     * A peer was discovered on the network.
     */
open func onPeerDiscovered(peerId: String, displayName: String, addresses: [String], isConnected: Bool)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_peer_discovered(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(displayName),
        FfiConverterSequenceString.lower(addresses),
        FfiConverterBool.lower(isConnected),$0
    )
}
}

    /**
     * A peer disconnected or went offline.
     */
open func onPeerLost(peerId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_peer_lost(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),$0
    )
}
}

    /**
     * A pairing request was received from a peer.
     */
open func onPairingRequest(peerId: String, displayName: String, pin: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_pairing_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(displayName),
        FfiConverterString.lower(pin),$0
    )
}
}

    /**
     * A pairing request completed (accepted or rejected).
     */
open func onPairingComplete(peerId: String, success: Bool)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_pairing_complete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterBool.lower(success),$0
    )
}
}

    /**
     * Sync is now listening on the given multiaddress.
     */
open func onListening(address: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_listening(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
}
}

    /**
     * An error occurred in the sync engine.
     */
open func onError(code: Int32, message: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_error(
            self.uniffiCloneHandle(),
        FfiConverterInt32.lower(code),
        FfiConverterString.lower(message),$0
    )
}
}

    /**
     * A file chunk was received (append to local temp file).
     */
open func onFileChunk(requestId: String, fileName: String, fileSize: Int64, chunkIndex: Int32, totalChunks: Int32, data: Data)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_file_chunk(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(requestId),
        FfiConverterString.lower(fileName),
        FfiConverterInt64.lower(fileSize),
        FfiConverterInt32.lower(chunkIndex),
        FfiConverterInt32.lower(totalChunks),
        FfiConverterData.lower(data),$0
    )
}
}

    /**
     * File download completed (or failed).
     */
open func onFileDownloadComplete(requestId: String, filePath: String, success: Bool)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_clipboardobserver_on_file_download_complete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(requestId),
        FfiConverterString.lower(filePath),
        FfiConverterBool.lower(success),$0
    )
}
}



}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceClipboardObserver {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceClipboardObserver = UniffiVTableCallbackInterfaceClipboardObserver(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeClipboardObserver.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ClipboardObserver: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeClipboardObserver.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ClipboardObserver: handle missing in uniffiClone")
            }
        },
        onItemReceived: { (
            uniffiHandle: UInt64,
            item: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onItemReceived(
                     item: try FfiConverterTypeClipboardItem_lift(item)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onItemDeleted: { (
            uniffiHandle: UInt64,
            itemId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onItemDeleted(
                     itemId: try FfiConverterString.lift(itemId)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onItemUpdated: { (
            uniffiHandle: UInt64,
            item: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onItemUpdated(
                     item: try FfiConverterTypeClipboardItem_lift(item)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPeerDiscovered: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            displayName: RustBuffer,
            addresses: RustBuffer,
            isConnected: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPeerDiscovered(
                     peerId: try FfiConverterString.lift(peerId),
                     displayName: try FfiConverterString.lift(displayName),
                     addresses: try FfiConverterSequenceString.lift(addresses),
                     isConnected: try FfiConverterBool.lift(isConnected)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPeerLost: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPeerLost(
                     peerId: try FfiConverterString.lift(peerId)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPairingRequest: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            displayName: RustBuffer,
            pin: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPairingRequest(
                     peerId: try FfiConverterString.lift(peerId),
                     displayName: try FfiConverterString.lift(displayName),
                     pin: try FfiConverterString.lift(pin)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPairingComplete: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            success: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPairingComplete(
                     peerId: try FfiConverterString.lift(peerId),
                     success: try FfiConverterBool.lift(success)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onListening: { (
            uniffiHandle: UInt64,
            address: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onListening(
                     address: try FfiConverterString.lift(address)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            code: Int32,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     code: try FfiConverterInt32.lift(code),
                     message: try FfiConverterString.lift(message)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onFileChunk: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            fileName: RustBuffer,
            fileSize: Int64,
            chunkIndex: Int32,
            totalChunks: Int32,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onFileChunk(
                     requestId: try FfiConverterString.lift(requestId),
                     fileName: try FfiConverterString.lift(fileName),
                     fileSize: try FfiConverterInt64.lift(fileSize),
                     chunkIndex: try FfiConverterInt32.lift(chunkIndex),
                     totalChunks: try FfiConverterInt32.lift(totalChunks),
                     data: try FfiConverterData.lift(data)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onFileDownloadComplete: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            filePath: RustBuffer,
            success: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeClipboardObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onFileDownloadComplete(
                     requestId: try FfiConverterString.lift(requestId),
                     filePath: try FfiConverterString.lift(filePath),
                     success: try FfiConverterBool.lift(success)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceClipboardObserver> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceClipboardObserver>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitClipboardObserver() {
    uniffi_manis_pocket_core_fn_init_callback_vtable_clipboardobserver(UniffiCallbackInterfaceClipboardObserver.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClipboardObserver: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ClipboardObserver>()

    typealias FfiType = UInt64
    typealias SwiftType = ClipboardObserver

    public static func lift(_ handle: UInt64) throws -> ClipboardObserver {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ClipboardObserverImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ClipboardObserver) -> UInt64 {
         if let rustImpl = value as? ClipboardObserverImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClipboardObserver {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ClipboardObserver, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardObserver_lift(_ handle: UInt64) throws -> ClipboardObserver {
    return try FfiConverterTypeClipboardObserver.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardObserver_lower(_ value: ClipboardObserver) -> UInt64 {
    return FfiConverterTypeClipboardObserver.lower(value)
}






/**
 * Central coordinator for clipboard history management.
 * Owns persistence (Storage), sync (SyncEngine), and search/sort.
 *
 * # Sync Group & Permissions
 *
 * Devices that pair form a **group**. Rules:
 * - Only one admin per group. The first device to pair becomes admin.
 * - Admin can transfer admin role to any member (promote_to_admin).
 * - Admin can remove members; regular members cannot remove anyone.
 * - A device belongs to at most one group; must leave before joining another.
 */
public protocol HistoryManagerProtocol: AnyObject, Sendable {

    /**
     * Add a new clipboard item. Handles deduplication and size limiting.
     * Rejects items that have no meaningful content.
     */
    func add(item: ClipboardItem, maxSize: Int32, isUnlimited: Bool) throws  -> ClipboardItem

    func clearAll() throws  -> UInt64

    func clearUnpinned() throws  -> UInt64

    func count() throws  -> Int64

    func delete(id: String) throws

    /**
     * Get all paired peers with their metadata (ID, name, admin status, online status).
     * Returns JSON strings — each is `{"peerId":..., "displayName":..., "isAdmin":..., "isOnline":...}`.
     */
    func getPairedPeers()  -> [String]

    /**
     * Load all items from storage.
     */
    func load() throws  -> [ClipboardItem]

    func migrateFromSwiftdata(swiftdataPath: String) throws  -> UInt64

    /**
     * Remove a paired peer.
     */
    func removePairedPeer(peerId: String)

    /**
     * Request a file download from a peer.
     */
    func requestFile(peerId: String, filePath: String)

    func savePairedPeer(peerId: String, displayName: String, isAdmin: Bool)

    func search(query: String, items: [ClipboardItem], mode: SearchMode)  -> [SearchResult]

    func sort(items: [ClipboardItem], sortBy: SortBy, pinToTop: Bool)  -> [ClipboardItem]

    /**
     * Start the P2P sync engine. The observer receives all sync events.
     */
    func startSync(deviceName: String, deviceId: String, observer: ClipboardObserver) throws

    /**
     * Stop the sync engine.
     */
    func stopSync() throws

    func storageSizeBytes(dbPath: String)  -> Int64

    func syncAcceptPairing(peerId: String, pin: String)

    func syncAddPeerAddress(address: String)

    /**
     * Broadcast a deletion to synced peers.
     */
    func syncBroadcastDeletion(itemId: String)

    /**
     * Broadcast a newly copied item to synced peers.
     */
    func syncBroadcastItem(item: ClipboardItem)

    /**
     * Broadcast an update to synced peers.
     */
    func syncBroadcastUpdate(item: ClipboardItem)

    /**
     * Restart discovery to find new peers.
     */
    func syncRefreshDiscovery()

    func syncRejectPairing(peerId: String)

    func syncRequestPairing(peerId: String)

    func syncStartDiscovery()

    func syncStopDiscovery()

    func syncUnpair(peerId: String)

    func togglePin(id: String, availablePins: [String]) throws  -> ClipboardItem

    func updateItemText(id: String, newText: String) throws  -> ClipboardItem

}
/**
 * Central coordinator for clipboard history management.
 * Owns persistence (Storage), sync (SyncEngine), and search/sort.
 *
 * # Sync Group & Permissions
 *
 * Devices that pair form a **group**. Rules:
 * - Only one admin per group. The first device to pair becomes admin.
 * - Admin can transfer admin role to any member (promote_to_admin).
 * - Admin can remove members; regular members cannot remove anyone.
 * - A device belongs to at most one group; must leave before joining another.
 */
open class HistoryManager: HistoryManagerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_manis_pocket_core_fn_clone_historymanager(self.handle, $0) }
    }
public convenience init(dbPath: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_constructor_historymanager_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_manis_pocket_core_fn_free_historymanager(handle, $0) }
    }




    /**
     * Add a new clipboard item. Handles deduplication and size limiting.
     * Rejects items that have no meaningful content.
     */
open func add(item: ClipboardItem, maxSize: Int32, isUnlimited: Bool)throws  -> ClipboardItem  {
    return try  FfiConverterTypeClipboardItem_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_add(
            self.uniffiCloneHandle(),
        FfiConverterTypeClipboardItem_lower(item),
        FfiConverterInt32.lower(maxSize),
        FfiConverterBool.lower(isUnlimited),$0
    )
})
}

open func clearAll()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_clear_all(
            self.uniffiCloneHandle(),$0
    )
})
}

open func clearUnpinned()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_clear_unpinned(
            self.uniffiCloneHandle(),$0
    )
})
}

open func count()throws  -> Int64  {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_count(
            self.uniffiCloneHandle(),$0
    )
})
}

open func delete(id: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}

    /**
     * Get all paired peers with their metadata (ID, name, admin status, online status).
     * Returns JSON strings — each is `{"peerId":..., "displayName":..., "isAdmin":..., "isOnline":...}`.
     */
open func getPairedPeers() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_get_paired_peers(
            self.uniffiCloneHandle(),$0
    )
})
}

    /**
     * Load all items from storage.
     */
open func load()throws  -> [ClipboardItem]  {
    return try  FfiConverterSequenceTypeClipboardItem.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_load(
            self.uniffiCloneHandle(),$0
    )
})
}

open func migrateFromSwiftdata(swiftdataPath: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_migrate_from_swiftdata(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(swiftdataPath),$0
    )
})
}

    /**
     * Remove a paired peer.
     */
open func removePairedPeer(peerId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_remove_paired_peer(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),$0
    )
}
}

    /**
     * Request a file download from a peer.
     */
open func requestFile(peerId: String, filePath: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_request_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(filePath),$0
    )
}
}

open func savePairedPeer(peerId: String, displayName: String, isAdmin: Bool)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_save_paired_peer(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(displayName),
        FfiConverterBool.lower(isAdmin),$0
    )
}
}

open func search(query: String, items: [ClipboardItem], mode: SearchMode) -> [SearchResult]  {
    return try!  FfiConverterSequenceTypeSearchResult.lift(try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_search(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterSequenceTypeClipboardItem.lower(items),
        FfiConverterTypeSearchMode_lower(mode),$0
    )
})
}

open func sort(items: [ClipboardItem], sortBy: SortBy, pinToTop: Bool) -> [ClipboardItem]  {
    return try!  FfiConverterSequenceTypeClipboardItem.lift(try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sort(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeClipboardItem.lower(items),
        FfiConverterTypeSortBy_lower(sortBy),
        FfiConverterBool.lower(pinToTop),$0
    )
})
}

    /**
     * Start the P2P sync engine. The observer receives all sync events.
     */
open func startSync(deviceName: String, deviceId: String, observer: ClipboardObserver)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_start_sync(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(deviceName),
        FfiConverterString.lower(deviceId),
        FfiConverterTypeClipboardObserver_lower(observer),$0
    )
}
}

    /**
     * Stop the sync engine.
     */
open func stopSync()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_stop_sync(
            self.uniffiCloneHandle(),$0
    )
}
}

open func storageSizeBytes(dbPath: String) -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_storage_size_bytes(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(dbPath),$0
    )
})
}

open func syncAcceptPairing(peerId: String, pin: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_accept_pairing(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(pin),$0
    )
}
}

open func syncAddPeerAddress(address: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_add_peer_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
}
}

    /**
     * Broadcast a deletion to synced peers.
     */
open func syncBroadcastDeletion(itemId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_broadcast_deletion(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(itemId),$0
    )
}
}

    /**
     * Broadcast a newly copied item to synced peers.
     */
open func syncBroadcastItem(item: ClipboardItem)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_broadcast_item(
            self.uniffiCloneHandle(),
        FfiConverterTypeClipboardItem_lower(item),$0
    )
}
}

    /**
     * Broadcast an update to synced peers.
     */
open func syncBroadcastUpdate(item: ClipboardItem)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_broadcast_update(
            self.uniffiCloneHandle(),
        FfiConverterTypeClipboardItem_lower(item),$0
    )
}
}

    /**
     * Restart discovery to find new peers.
     */
open func syncRefreshDiscovery()  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_refresh_discovery(
            self.uniffiCloneHandle(),$0
    )
}
}

open func syncRejectPairing(peerId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_reject_pairing(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),$0
    )
}
}

open func syncRequestPairing(peerId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_request_pairing(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),$0
    )
}
}

open func syncStartDiscovery()  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_start_discovery(
            self.uniffiCloneHandle(),$0
    )
}
}

open func syncStopDiscovery()  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_stop_discovery(
            self.uniffiCloneHandle(),$0
    )
}
}

open func syncUnpair(peerId: String)  {try! rustCall() {
    uniffi_manis_pocket_core_fn_method_historymanager_sync_unpair(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peerId),$0
    )
}
}

open func togglePin(id: String, availablePins: [String])throws  -> ClipboardItem  {
    return try  FfiConverterTypeClipboardItem_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_toggle_pin(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterSequenceString.lower(availablePins),$0
    )
})
}

open func updateItemText(id: String, newText: String)throws  -> ClipboardItem  {
    return try  FfiConverterTypeClipboardItem_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_manis_pocket_core_fn_method_historymanager_update_item_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(newText),$0
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHistoryManager: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HistoryManager

    public static func lift(_ handle: UInt64) throws -> HistoryManager {
        return HistoryManager(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HistoryManager) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HistoryManager {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HistoryManager, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryManager_lift(_ handle: UInt64) throws -> HistoryManager {
    return try FfiConverterTypeHistoryManager.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryManager_lower(_ value: HistoryManager) -> UInt64 {
    return FfiConverterTypeHistoryManager.lower(value)
}




/**
 * A single content entry within a clipboard item (e.g., text, image data, file URL).
 */
public struct ClipboardContent: Equatable, Hashable {
    /**
     * UTI string like "public.utf8-plain-text", "public.png", etc.
     */
    public var contentType: String
    /**
     * Raw bytes of the content value.
     */
    public var value: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * UTI string like "public.utf8-plain-text", "public.png", etc.
         */contentType: String,
        /**
         * Raw bytes of the content value.
         */value: Data?) {
        self.contentType = contentType
        self.value = value
    }




}

#if compiler(>=6)
extension ClipboardContent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClipboardContent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClipboardContent {
        return
            try ClipboardContent(
                contentType: FfiConverterString.read(from: &buf),
                value: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: ClipboardContent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.contentType, into: &buf)
        FfiConverterOptionData.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardContent_lift(_ buf: RustBuffer) throws -> ClipboardContent {
    return try FfiConverterTypeClipboardContent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardContent_lower(_ value: ClipboardContent) -> RustBuffer {
    return FfiConverterTypeClipboardContent.lower(value)
}


/**
 * A clipboard history item — the central domain model.
 */
public struct ClipboardItem: Equatable, Hashable {
    public var id: String
    public var application: String?
    /**
     * Unix epoch milliseconds
     */
    public var firstCopiedAt: Int64
    /**
     * Unix epoch milliseconds
     */
    public var lastCopiedAt: Int64
    public var numberOfCopies: Int32
    /**
     * Pin key character (e.g., "b", "c"), or None if unpinned
     */
    public var pin: String?
    public var title: String
    public var contents: [ClipboardContent]
    /**
     * Unix epoch milliseconds
     */
    public var syncTimestamp: Int64
    public var syncSource: String?
    public var syncDeleted: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, application: String?,
        /**
         * Unix epoch milliseconds
         */firstCopiedAt: Int64,
        /**
         * Unix epoch milliseconds
         */lastCopiedAt: Int64, numberOfCopies: Int32,
        /**
         * Pin key character (e.g., "b", "c"), or None if unpinned
         */pin: String?, title: String, contents: [ClipboardContent],
        /**
         * Unix epoch milliseconds
         */syncTimestamp: Int64, syncSource: String?, syncDeleted: Bool) {
        self.id = id
        self.application = application
        self.firstCopiedAt = firstCopiedAt
        self.lastCopiedAt = lastCopiedAt
        self.numberOfCopies = numberOfCopies
        self.pin = pin
        self.title = title
        self.contents = contents
        self.syncTimestamp = syncTimestamp
        self.syncSource = syncSource
        self.syncDeleted = syncDeleted
    }




}

#if compiler(>=6)
extension ClipboardItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClipboardItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClipboardItem {
        return
            try ClipboardItem(
                id: FfiConverterString.read(from: &buf),
                application: FfiConverterOptionString.read(from: &buf),
                firstCopiedAt: FfiConverterInt64.read(from: &buf),
                lastCopiedAt: FfiConverterInt64.read(from: &buf),
                numberOfCopies: FfiConverterInt32.read(from: &buf),
                pin: FfiConverterOptionString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                contents: FfiConverterSequenceTypeClipboardContent.read(from: &buf),
                syncTimestamp: FfiConverterInt64.read(from: &buf),
                syncSource: FfiConverterOptionString.read(from: &buf),
                syncDeleted: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ClipboardItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.application, into: &buf)
        FfiConverterInt64.write(value.firstCopiedAt, into: &buf)
        FfiConverterInt64.write(value.lastCopiedAt, into: &buf)
        FfiConverterInt32.write(value.numberOfCopies, into: &buf)
        FfiConverterOptionString.write(value.pin, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterSequenceTypeClipboardContent.write(value.contents, into: &buf)
        FfiConverterInt64.write(value.syncTimestamp, into: &buf)
        FfiConverterOptionString.write(value.syncSource, into: &buf)
        FfiConverterBool.write(value.syncDeleted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardItem_lift(_ buf: RustBuffer) throws -> ClipboardItem {
    return try FfiConverterTypeClipboardItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardItem_lower(_ value: ClipboardItem) -> RustBuffer {
    return FfiConverterTypeClipboardItem.lower(value)
}


/**
 * Half-open Unicode scalar range in the original title for search highlighting.
 */
public struct MatchRange: Equatable, Hashable {
    public var start: Int64
    public var end: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: Int64, end: Int64) {
        self.start = start
        self.end = end
    }




}

#if compiler(>=6)
extension MatchRange: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMatchRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MatchRange {
        return
            try MatchRange(
                start: FfiConverterInt64.read(from: &buf),
                end: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MatchRange, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.start, into: &buf)
        FfiConverterInt64.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMatchRange_lift(_ buf: RustBuffer) throws -> MatchRange {
    return try FfiConverterTypeMatchRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMatchRange_lower(_ value: MatchRange) -> RustBuffer {
    return FfiConverterTypeMatchRange.lower(value)
}


/**
 * Result of a search operation.
 */
public struct SearchResult: Equatable, Hashable {
    public var item: ClipboardItem
    /**
     * Fuzzy match score (lower is better). None for exact/regex matches.
     */
    public var score: Double?
    /**
     * Unicode scalar ranges in the original title that match the query.
     */
    public var ranges: [MatchRange]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(item: ClipboardItem,
        /**
         * Fuzzy match score (lower is better). None for exact/regex matches.
         */score: Double?,
        /**
         * Unicode scalar ranges in the original title that match the query.
         */ranges: [MatchRange]) {
        self.item = item
        self.score = score
        self.ranges = ranges
    }




}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                item: FfiConverterTypeClipboardItem.read(from: &buf),
                score: FfiConverterOptionDouble.read(from: &buf),
                ranges: FfiConverterSequenceTypeMatchRange.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterTypeClipboardItem.write(value.item, into: &buf)
        FfiConverterOptionDouble.write(value.score, into: &buf)
        FfiConverterSequenceTypeMatchRange.write(value.ranges, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


public enum CoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Storage(msg: String
    )
    case NotFound(id: String
    )
    case InvalidArg(msg: String
    )
    case Sync(msg: String
    )






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension CoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Storage(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidArg(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Sync(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {





        case let .Storage(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)


        case let .NotFound(id):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(id, into: &buf)


        case let .InvalidArg(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)


        case let .Sync(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SearchMode: Equatable, Hashable {

    case exact
    case fuzzy
    case regexp
    case mixed





}

#if compiler(>=6)
extension SearchMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchMode: FfiConverterRustBuffer {
    typealias SwiftType = SearchMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .exact

        case 2: return .fuzzy

        case 3: return .regexp

        case 4: return .mixed

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchMode, into buf: inout [UInt8]) {
        switch value {


        case .exact:
            writeInt(&buf, Int32(1))


        case .fuzzy:
            writeInt(&buf, Int32(2))


        case .regexp:
            writeInt(&buf, Int32(3))


        case .mixed:
            writeInt(&buf, Int32(4))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchMode_lift(_ buf: RustBuffer) throws -> SearchMode {
    return try FfiConverterTypeSearchMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchMode_lower(_ value: SearchMode) -> RustBuffer {
    return FfiConverterTypeSearchMode.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SortBy: Equatable, Hashable {

    case lastCopiedAt
    case firstCopiedAt
    case numberOfCopies





}

#if compiler(>=6)
extension SortBy: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSortBy: FfiConverterRustBuffer {
    typealias SwiftType = SortBy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SortBy {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .lastCopiedAt

        case 2: return .firstCopiedAt

        case 3: return .numberOfCopies

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SortBy, into buf: inout [UInt8]) {
        switch value {


        case .lastCopiedAt:
            writeInt(&buf, Int32(1))


        case .firstCopiedAt:
            writeInt(&buf, Int32(2))


        case .numberOfCopies:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSortBy_lift(_ buf: RustBuffer) throws -> SortBy {
    return try FfiConverterTypeSortBy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSortBy_lower(_ value: SortBy) -> RustBuffer {
    return FfiConverterTypeSortBy.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeClipboardContent: FfiConverterRustBuffer {
    typealias SwiftType = [ClipboardContent]

    public static func write(_ value: [ClipboardContent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeClipboardContent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ClipboardContent] {
        let len: Int32 = try readInt(&buf)
        var seq = [ClipboardContent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeClipboardContent.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeClipboardItem: FfiConverterRustBuffer {
    typealias SwiftType = [ClipboardItem]

    public static func write(_ value: [ClipboardItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeClipboardItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ClipboardItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [ClipboardItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeClipboardItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMatchRange: FfiConverterRustBuffer {
    typealias SwiftType = [MatchRange]

    public static func write(_ value: [MatchRange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMatchRange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MatchRange] {
        let len: Int32 = try readInt(&buf)
        var seq = [MatchRange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMatchRange.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_manis_pocket_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_add() != 56911) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_clear_all() != 15791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_clear_unpinned() != 46938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_count() != 25432) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_delete() != 22226) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_get_paired_peers() != 36004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_load() != 54083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_migrate_from_swiftdata() != 2055) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_remove_paired_peer() != 41724) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_request_file() != 39782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_save_paired_peer() != 29700) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_search() != 34005) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sort() != 37833) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_start_sync() != 33426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_stop_sync() != 29672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_storage_size_bytes() != 52352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_accept_pairing() != 21862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_add_peer_address() != 49223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_broadcast_deletion() != 1779) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_broadcast_item() != 60418) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_broadcast_update() != 57751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_refresh_discovery() != 49637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_reject_pairing() != 41431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_request_pairing() != 41726) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_start_discovery() != 6184) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_stop_discovery() != 10096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_sync_unpair() != 13288) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_toggle_pin() != 39233) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_historymanager_update_item_text() != 42189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_item_received() != 57985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_item_deleted() != 56895) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_item_updated() != 31585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_peer_discovered() != 30420) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_peer_lost() != 27753) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_pairing_request() != 40901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_pairing_complete() != 19982) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_listening() != 63339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_error() != 47623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_file_chunk() != 33966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_method_clipboardobserver_on_file_download_complete() != 34217) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_manis_pocket_core_checksum_constructor_historymanager_new() != 38126) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitClipboardObserver()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureManisPocketCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all